---
- hosts: localhost
  gather_facts: false
  vars:
    git_user_name: "pypeaday"
    git_user_email: "pypeaday@pype.dev"
  # vars_prompt:
  #   - name: "git_user_name"
  #     prompt: "What is your git user name?"
  #     private: false
  #   - name: "git_user_email"
  #     prompt: "What is your git user email?"
  #     private: false
  tasks:
    - name: Set git config values
      git_config:
        scope: global
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: "user.name", value: "{{ git_user_name }}" }
        - { name: "user.email", value: "{{ git_user_email }}" }
        - { name: "credential.helper", value: "store" }
        - { name: "safe.directory", value: "/home/vscode/devcontainer" }
        - { name: "init.defaultBranch", value: "main" }

